substitutions:
  name: "jc8012"
  friendly_name: "JC8012 Screen"

wifi:
  ssid: "你的WiFi名称"
  password: "你的WiFi密码"
  fast_connect: true

packages:
  device: https://github.com/jtenniswood/esphome-lvgl/blob/main/guition-esp32-p4-jc8012p4a1/package.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-p4
  framework:
    type: esp-idf
